ALTER TABLE "Group" ADD COLUMN "user_sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Subgroup" ADD COLUMN "user_sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Entry" ADD COLUMN "user_sort" INTEGER NOT NULL DEFAULT 0;
